bak

diff --git a/bin/mycpufreq b/bin/mycpufreq
--- a/bin/mycpufreq
+++ b/bin/mycpufreq
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-set -eu
+set -e
 
 if [ ! -e /sys/bus/cpu/devices/cpu0/cpufreq/scaling_governor ]; then
     >&2 echo "ERROR: cpufreq driver file doesn't exist!"
@@ -9,21 +9,21 @@ fi
 
 # specifically for tigerlake intel:
 case $1 in
-  "") cat /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor ;;
-    powersave)
-      echo powersave | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor
-      echo power | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference
-      ;;
-    schedutil)
-      echo schedutil | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor
-      echo default | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference
-      ;;
-    performance)
-      echo performance | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor
-      echo performance | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference
-      ;;
-    *)
-      >&2 echo "ERROR: invalid argument '$1'"
-      exit 1
-      ;;
+  "") cat /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference ;;
+  powersave)
+    echo powersave | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor
+    echo power | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference
+    ;;
+  schedutil)
+    echo schedutil | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor
+    echo default | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference
+    ;;
+  performance)
+    echo performance | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor
+    echo performance | doas tee /sys/bus/cpu/devices/cpu*/cpufreq/energy_performance_preference
+    ;;
+  *)
+    >&2 echo "ERROR: invalid argument '$1'"
+    exit 1
+    ;;
 esac
